# Generated by Django 6.0.5 on 2026-05-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_home_index',
            field=models.BooleanField(default=False),
        ),
    ]
